package com.tiedup.remake.worldgen;

import com.tiedup.remake.core.TiedUpMod;
import net.minecraft.core.registries.Registries;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureProcessorType;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

/**
 * Registry for custom structure processors.
 *
 * Phase: Kidnapper Revamp - Cell System
 */
public class ModProcessors {

    public static final DeferredRegister<StructureProcessorType<?>> PROCESSORS =
        DeferredRegister.create(
            Registries.STRUCTURE_PROCESSOR,
            TiedUpMod.MOD_ID
        );

    public static final RegistryObject<
        StructureProcessorType<MarkerProcessor>
    > MARKER_PROCESSOR = PROCESSORS.register(
        "marker_processor",
        () -> () -> MarkerProcessor.CODEC
    );
}
