package com.tiedup.remake.blocks;

import net.minecraft.world.level.block.DoorBlock;
import net.minecraft.world.level.block.SoundType;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.material.MapColor;

/**
 * Cell Door Block - Iron-like door that cannot be opened by hand.
 *
 *
 * Features:
 * - Cannot be opened by clicking (requires redstone)
 * - Uses iron door behavior
 * - Sturdy construction
 *
 * Based on original BlockKidnapDoorBase from 1.12.2
 */
public class BlockCellDoor extends DoorBlock {

    public BlockCellDoor() {
        super(
            BlockBehaviour.Properties.of()
                .mapColor(MapColor.METAL)
                .strength(5.0f, 45.0f)
                .sound(SoundType.METAL)
                .requiresCorrectToolForDrops()
                .noOcclusion(),
            BlockSetType.IRON // J'ai remis moi même
        );
    }
}
