package com.tiedup.remake.v2;

import com.tiedup.remake.core.TiedUpMod;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

/**
 * V2 Item Registration.
 * Block items for V2 blocks.
 */
public class V2Items {

    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(
        ForgeRegistries.ITEMS,
        TiedUpMod.MOD_ID
    );

    // BLOCK ITEMS

    public static final RegistryObject<Item> PET_BOWL = ITEMS.register(
        "pet_bowl",
        () -> new BlockItem(V2Blocks.PET_BOWL.get(), new Item.Properties())
    );

    public static final RegistryObject<Item> PET_BED = ITEMS.register(
        "pet_bed",
        () -> new BlockItem(V2Blocks.PET_BED.get(), new Item.Properties())
    );

    public static final RegistryObject<Item> PET_CAGE = ITEMS.register(
        "pet_cage",
        () -> new BlockItem(V2Blocks.PET_CAGE.get(), new Item.Properties())
    );
}
