package com.tiedup.remake.client.network;

import com.tiedup.remake.client.gui.screens.PetRequestScreen;
import java.util.List;
// import com.tiedup.remake.client.gui.screens.ConversationScreen; // DISABLED: Conversation system not in use
// import com.tiedup.remake.dialogue.conversation.ConversationTopic; // DISABLED: Conversation system not in use
import net.minecraft.client.Minecraft;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

/**
 * Client-side packet handling helper.
 *
 * This class is ONLY loaded on the client, preventing server-side crashes
 * from attempting to load client-only classes like Screen.
 */
@OnlyIn(Dist.CLIENT)
public class ClientPacketHandler {

    /**
     * Open the conversation screen.
     * DISABLED: Conversation system not in use
     */
    /*
    public static void openConversationScreen(int entityId, String npcName, List<ConversationTopic> topics) {
        Minecraft.getInstance().setScreen(
            new ConversationScreen(entityId, npcName, topics)
        );
    }
    */

    /**
     * Open the pet request menu.
     */
    public static void openPetRequestScreen(int entityId, String masterName) {
        Minecraft.getInstance().setScreen(
            new PetRequestScreen(entityId, masterName)
        );
    }
}
